import Head from 'next/head'
import Image from 'next/image'
import TagLiner from '../components/tagLiner'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TagLiner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TagLiner />
      </main>

      <footer className={styles.footer}>
        Copyright &#169; {new Date().getFullYear()} TagLiner
      </footer>
    </div>
  )
}
